REFPLTB-1787: Wifi and LAN clients are not getting internet from Turris (#479)
Reason for change: Get_Device_Mode API is called outside WAN_FAILOVER_SUPPORTED block.
Causing undefined reference to Get_Device_Mode during CcspPandM startup
Test procedure: Found that DM is initialized for CcspPandM
Risks: Low

Signed-off-by: Manigandan Gopalakrishnan <manigandan.gopalakrishnan@ltts.com>

Signed-off-by: Manigandan Gopalakrishnan <manigandan.gopalakrishnan@ltts.com>