Add RbusBuildFlagEnable DISTRO_FEATURES (#530)
It is needed to fix RDK Cellular Manager build errors
| RdkCellularManager/source/CellularManager/cellularmgr_cellular_apis.c:793:11: error: 'gRBUSSubListSt' undeclared (first use in this function)
|   793 |     if( ( gRBUSSubListSt.stRadioSignal.RSSISubFlag ) ||
|       |           ^~~~~~~~~~~~~~

after RdkCellularManager/+/82287 is merged.