REFPLTB-2531 : Latest turris build is breaking after improting of comcast change(87358) (#538)
Reason for change : Below errors are observed,
ERROR: openvswitch-2.17+AUTOINC+e206df08d2-r0 do_patch: Command Error: 'quilt --quiltrc
Applying patch CVE-2021-36980_fix.patch
patching file lib/ofp-actions.c
Hunk #1 FAILED at 4346.
Hunk #2 FAILED at 4373.
2 out of 2 hunks FAILED -- rejects in file lib/ofp-actions.c
patching file tests/automake.mk
Hunk #1 FAILED at 132.
1 out of 1 hunk FAILED -- rejects in file tests/automake.mk
patching file tests/fuzz-regression-list.at
Hunk #1 FAILED at 21.
1 out of 1 hunk FAILED -- rejects in file tests/fuzz-regression-list.at
The next patch would empty out the file tests/fuzz-regression/ofp_print_fuzzer-6540965472632832,
which is already empty!  Applying it anyway.
patching file tests/fuzz-regression/ofp_print_fuzzer-6540965472632832
Patch CVE-2021-36980_fix.patch does not apply (enforce with -f)
Test Procedure: bitbake openvswitch
Risks: Low

Signed-off-by: keerthana.p <keerthana.p@ltts.com>
Co-authored-by: keerthana.p <keerthana_pandurangan@comcast.com>