Fix ccsp-wifi-agent build errors after warnings are treated as errors
Due to meta-rdk-broadband/55979.
The build error is
| ../../../../../../../../../../rdkb/components/opensource/ccsp/CcspWifiAgent/source/TR-181/sbapi/cosa_wifi_sbapi_custom.h:84:0: error: COSA_DML_WIFI_FEATURE_LoadPsmDefaults redefined [-Werror]
|  #define COSA_DML_WIFI_FEATURE_LoadPsmDefaults       0
|
| <command-line>:0:0: note: this is the location of the previous definition

In Turris build COSA_DML_WIFI_FEATURE_LoadPsmDefaults is turned on by recipe, so the
only way to fix this error is to add -Wno-error