Fix BCI utopia build after WanFailOverSupportEnable DISTRO_FEATURES has been enabled. (#545)
The WAN_FAILOVER_SUPPORTED CFLAGS needs to be removed explicitly for bci builds,

Build error:
| Utopia/source/service_routed/service_routed.c:1059:23: error: 'last_broadcasted_prefix' undeclared (first use in this function)
|  1059 |             if(strlen(last_broadcasted_prefix) != 0)
|       |                       ^~~~~~~~~~~~~~~~~~~~~~~
| Utopia/source/service_routed/service_routed.c:1059:23: note: each undeclared identifier is reported only once for each function it appears in
| Makefile:476: recipe for target 'service_routed-service_routed.o' failed
| make[3]: *** [service_routed-service_routed.o] Error 1